name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # prevent run on fork
      - if: github.repository == 'gkd-kit/subscription'
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
